<?php
if(!defined('AT_ROOT')) exit;

$AT->output->title = 'News Archive';
$AT->output->printHeader(86400);


$AT->output->printTitleAndDesc('News Archive');

?>

<style type="text/css">
#news-archive div { margin-bottom: 0.5em; }
</style>
<div id="news-archive">
<?php

foreach(array(
	'27th Nov 2024' => 'Anidex as a source will be removed in about two weeks\' time. Nyaa and TokyoTosho will remain as sources.',
	'24th Sep 2024' => 'The secondary webserver should now be fully restored. Apologies for the extended downtime and thank you for your patience.',
	'23rd Sep 2024' => 'The secondary webserver is still currently down (links to torrents, attachments, NZBs, images and the feed/RSS will not work). I am currently trying to get a replacement server, but the host is taking their time on the matter unfortunately. Apologies for the extended downtime.',
	'19th Sep 2024' => 'Maintenance on the secondary webserver is planned to occur on 2024-09-21 06:00 GMT (affects attachments, screenshots, torrents, NZBs and feed). Downtime is expected to be around 1 hour, should no complications occur. UPDATE: server is currently experiencing boot failures, remaining downtime unknown.',
	'22nd Apr 2024' => 'There seems to be a large number of uploads being posted this season, particularly on weekends. This has led to long processing queues, which may take many hours for the server to go through. Apologies for the delays.',
	'5th Mar 2024' => '<s>The secondary webserver is currently down (affects attachments, screenshots, torrents, NZBs and feed). Waiting on a fix from the provider.</s> Apologies for the inconvenience.',
	'20th Nov 2023' => '<s>The updates server is currently unresponsive, meaning that updates will not occur</s> Issue now resolved. Sorry for the inconvenience.',
	'29th Dec 2021' => '<s>The storage server is currently syncing (rather slowly). New files won\'t show up until this is complete, which will likely take hours if not a day. This mostly affects links to new screenshots/attachments/NZBs/torrents.</s> Syncing complete, apologies for the delay.',
	'25th Jun 2021' => 'Today marks Anime Tosho\'s 10th anniversary - a milestone any <s>parent</s> admin would be proud of, and one I would\'ve sarcastically said AT could easily achieve. Despite <a href="https://web.archive.org/web/20110623230406/https://animetosho.org/">appearances</a>, <i>much</i> <span style="border-bottom: 1px dotted" title="have you seen our pile of dead links?">has changed</span> over this time period. A big thanks to all that have clicked, swiped and teasingly prodded this website over the years - your support means a lot towards making the servers feel loved and keeping them fit.',
	'2nd May 2021' => 'The secondary webserver may be taken down for some brief maintenance today/tomorrow. Feeds, screenshots, attachments and a few other things may become unavailable.',
	'23rd Mar 2021' => 'AnonFiles is capping uploads at 100GB/day. As such, uploads to AF will be restricted based on size, to try to stay within these limits.',
	'12th Jan 2021' => 'For the curious minded, there\'s now a page with info on <a href="'.AT::buildUrl('about', 'logistics').'">the running of Anime Tosho</a>.',
	'17th Feb 2019' => 'Most restrictions on <i>Direct</i> download links have been lifted, as the system is now deprecated and will likely removed in a few days. <a href="https://animetosho.org/feedback?page=310#comment14296">See here</a> for more info.',
	'7th Jul 2018' => 'Added a <a href="'.AT::buildUrl('animes').'">Series Updates</a> page, which lists items on the home page grouped by series.',
	'9th Apr 2018' => 'Feed (RSS2/ATOM/API) URLs have changed - please update any aggregators/clients that are using the old URL format. Previously such URLs started with <i>https://animetosho.org/feed/</i> which is now <i>https://feed.animetosho.org/</i>',
	'16th Feb 2018' => '<s>&quot;Direct&quot; download links (those which only show up for older files) are currently not working due to <a href="https://animetosho.org/view/dmonhiro-frame-arms-girl-bd-720p.n983249#comment78603">the underlying accounts\' subscriptions being revoked</a>. Sorry for the inconvenience</s> Back up thanks to <a href="https://animetosho.org/feedback?page=274#comment12335">a kind anon</a>!',
	'13th June 2017' => '<s>Users of the \'Direct\' links may have noticed that they do not work any more. The server is currently locked, and I am unsure when I can get it working again.</s> Direct link server now back up!',
	'21st May 2017' => 'Feeds can be generated off any torrent listing (including search) via the new feed icon to the right of the Nyaa Filter dropdown. Also a <a href="https://animetosho.org/feed/api">Newznab/Torznab feed</a> has been added.',
	'13th May 2017' => 'Whether it\'s for archival purposes, to create a better AnimeTosho or to satisfy statistical curiosities, I\'m providing daily database exports of some of AnimeTosho\'s data, which <a href="https://storage.animetosho.org/dbexport/">you can get from here</a>.',
	'3rd May 2017' => 'As many of you already know, Nyaa has been removed as a source, due to its shutdown. AniDex and HorribleSubs are now fetched instead. For those interested in a cache of recent uploads at Nyaa, including non-anime categories, I happen to have one available - <a href="https://animetosho.org/feedback?page=221#comment7935">see this comment</a>.',
	'8th April 2017' => 'Subtitles are now being rendered into screenshots from MKV files, including all those since the new screenshot system was introduced. These only appear in the full image (not the thumbnail), and by default, is set to render the first subtitle track in the file. SRT subtitles are currently not rendered.',
	'12th November 2016' => 'A new screenshot system is being trialed. It\'s pretty much like the old one, <s>except that subtitles never get rendered into the image</s>.',
	'29th October 2016' => '<s>The storage server is currently down, awaiting fixes from the hosting provider. Torrent download links, NZBs, image previews and attachments are unavailable until this is resolved.</s> Storage server appears to be working again',
	'20th March 2016' => 'We\'re currently having some issues with updates, which may be paused or intermittent today. I will try to resolve these as soon as possible.',
	'15th March 2016' => 'For Usenet users, Anime Tosho now generates <a href="https://en.wikipedia.org/wiki/NZB">NZBs</a> for all processed torrents. Being experimental, please report any issues/suggestions to the <a href="'.AT::buildUrl('feedback').'">feedback page</a>. The tools created to enable this have also been released, free to be used in whatever way you fancy: <a href="'.AT::buildUrl('app', 'nyuu').'">Nyuu</a> (flexible usenet binary poster) and <a href="'.AT::buildUrl('app', 'parpar').'">ParPar</a> (efficient PAR2 client).',
	'14th February 2016' => 'Registered users can now show their love for their favourite character by setting up a small display picture next to their comments (and a tag line too!). Visit the <a href="'.AT::buildUrl('usercp').'">account settings page</a> to see available options.',
	'31st March 2015' => '<s>All updates have been paused as there is a throughput problem at the moment. I hope to resolve this as soon as possible, but this may take a few days.</s> Issue should now be resolved.',
	'4th January 2015' => 'It has been pointed out that Go4Up appears to be appending zero bytes to the end of uploaded files. This shouldn\'t have any noticeable effects, other than causing CRC/hash checks to not match up. If matching hashes are important to you, you can trim the zeros off the end to get the original file. See <a href="https://animetosho.org/feedback?page=138#comment4246">this comment</a> for more info.',
	'19th February 2015' => 'All torrents under 16GB are now automatically fetched. Select files up to 32GB are also automatically fetched. These limits are experimental and may be reverted later.',
	'20th January 2015' => '<s>A number of users have reported issues with connecting to Anime Tosho. Unfortunately I haven\'t been able to replicate such issues, but if you\'re experiencing them, and want to help out, <a href="https://animetosho.org/feedback?page=141#comment4344">please see this post</a>.</s> Issue appears to be resolved now, thanks to everyone who helped!',
	'6th January 2015' => 'AT now fetches selected files from TokyoTosho\'s Batch category. The filter is somewhat experimental and may fetch non-English or non-anime releases, but we hope to improve on this.',
	'25th September 2014' => 'DevHost appears to have blocked us, so unfortunately we cannot continue uploading there. <s>Suggestions for an alternative host to replace DevHost <a href="https://animetosho.org/feedback">are welcome</a>.</s> Thanks for all the suggested alternatives!',
	'13th July 2014' => 'Storage server <s>is currently down (affects screenshot previews as well as subtitle downloads). We will try to resolve the issue as soon as possible</s> is back up. Apologies for the inconvenience.',
	'10th June 2014' => 'MultiUpload has been disabled as all their links appear to be redirecting to crapware.',
	'26nd June 2014' => 'DNS entries have been updated. If you\'re seeing this message (that is, able to access animetosho.org), your DNS resolver has likely caught up with the changes. We apologise for any downtime caused by a DNS change.',
	'22nd June 2014' => 'This website\'s domain (animetosho.org address) is going to be updated in a few days. Hopefully the transition goes smoothly, but if this site becomes inaccessible, updates will be posted to <a href="http://yukinoshita.eu/ATUpdates.txt">http://yukinoshita.eu/ATUpdates.txt</a> (thanks to Tibb for providing the page)',
	'21st May 2014' => 'It seems that FireDrive (marked as PutLocker here) has deleted our premium account, which means that these links are now all broken. No reason was given for the deletion, and they don\'t respond to emails - clearly they don\'t care about their paying customers. From my anecdotal case, I recommend avoiding using FireDrive\'s paid accounts (if you\'re paying for something, you definitely want support to be responsive) as well as putting anything critical on their accounts (if you don\'t like the idea of it being deleted for no apparent reason). Of course, they\'re still great for just sharing files that you don\'t mind disappearing.',
	'1st May 2014' => 'EmbedUpload has blocked the server, so it can no longer be uploaded to.',
	'4th April 2014' => 'Everything should be back up and running now. If you notice anything that got missed, please <a href="https://animetosho.org/feedback">post them here</a>.',
	'3rd April 2014' => 'The disk on the updates server has died, so no updates will be coming through. It will probably be a few days before I can get updates back up and running again. Further information will be posted here. Apologies for any inconvenience.<br />UPDATE: Updates partially restored.',
	//'1st April 2014' => '<b>AnimeTosho is finally <a href="'.AT::buildUrl('about','endofbeta').'">going out of beta</a>!</b> <u>Big changes</u> will be made, so <a href="'.AT::buildUrl('about','endofbeta').'">click here</a> for the full details on this exciting development!<hr />',
	'30th March 2014' => 'Extracted subtitles/attachments system has been changed, any comments/feedback/issues on it, <a href="https://animetosho.org/feedback">post them here</a>. This change only affects newer files. Note that download resuming is currently not supported on the <i>All Attachments</i> link.<br /><a href="https://mirror.animetosho.org/">Backup/mirror site</a> has also been restored.',
	'24th February 2014' => 'Batch fetching size limit has been increased from 3GB to 8GB.',
	'17th February 2014' => 'AnonFiles has restricted its supported file types (even MKV is not allowed, despite what is mentioned in the allowed extensions list), so is no longer being uploaded to.',
	'31st January 2014' => 'Mega no longer allows sharing anonymously uploaded files, and hence, has been removed as an upload host',
	'2nd February 2013' => 'Added an <a href="https://animetosho.org/episodes">experimental episodes listing page</a>. This is probably unreliable but may be useful to someone.',
) as $date => $msg) {
	echo '<div', (TIME_NOW - strtotime($date) < 86400*3 ? ' style="font-size: 1.2em;"':''), '><strong>', $date, '</strong>: ', $msg, '</div>';
}

?>

<div><strong>23rd September 2013</strong>: Apologies for all the recent downtimes. I'm hoping it'll get better, but regardless, <s>I've created a <a href="https://mirror.animetosho.org/">backup mirror at <em>mirror.animetosho.org</em></a> for whever this main server becomes inaccessible</s>.</div>
<div><strong>8th July 2013</strong>: The search function has been modified a bit. It's still being developed, so there'll probably be further changes (watch here for updates) but any issues/feedback/problems, please <a href="https://animetosho.org/feedback">post them here</a>.</div>
<div><strong>18th June 2013</strong>: Added <a href="/about/filtseries">a list of filtered out series</a>.</div>
<div><strong>10th June 2013</strong>: For those interested in polls (but not telemarketers) <a style="text-decoration: line-through;" href="http://poll.pollcode.com/65pek">here's one about file hosts</a> <a href="http://poll.pollcode.com/9becg">new improved link</a>. Courtesy of <a href="https://animetosho.org/feedback?page=70#comment1969">these people here</a>.</div>
<div><span style="color: red;"><strong>1st April 2013</strong>: Users have been complaining that we list too many files, making it difficult to find what they are looking for. We've thus decided to only display the most popular shows, making it easier for everyone to find what they're actually looking for. And if what you're looking for isn't shown here, try looking for something that is shown here. Oh, and TokyoTosho fetching has been temporarily disabled.</span></div>
<div><strong>21st March 2013</strong>: The 7-Zip encoding has been changed for newer files. This newer encoding should limit the impact of random corruptions, although it won't reduce the chance of them occurring.</div>
<div><strong>12th February 2013</strong>: A warning to those trying out AnonFiles: AF seem to be randomly corrupting files. This may result in a CRC error when trying to extract the 7-Zip file. Re-downloading from AF may give you a working file, or it could give you a file corrupted in a different way (have confirmed the latter activity). Because of this, AF will most likely be removed soon.</div>
<div><strong>10th February 2013</strong>: PeejeShare has been removed as it's obviously rarely succeeding. Tibb seems to be having greater success; you can find his links in comments made to many files here. I'd like to take the opportunity to thank all the commenters who have gone to the effort of providing alternative links. In exchange for PeejeShare, we shall be testing AnonFiles.</div>
<div><strong>20th November 2012</strong>: The way files are split, when uploaded to various hosts, has been changed. Rather than split at size boundaries, splitting is now done evenly. For example, if the max file size for a particular host was 500MB, a 600MB file would be split into 500/100MB parts, but now would be split 300/300MB. This means that, for future uploads, parts amongst services should be interchangeable <u>if</u> they have the same number of parts (and are of the same format).</div>
<div><strong>13th October 2012</strong>: We have been blocked by ExoShare.</div>
<div><strong>20th September 2012</strong>: If you haven't noticed, PeejeShare has been removed as they seem to randomly remove files. Minus has been temporarily disabled as they've broken something too and need to be fixed. It seems that every host has messed us up in some way this week.</div>
<div><strong>31st August 2012</strong>: In an attempt to save some links, PeejeShare links are currently only shown to registered users.</div>
<div><strong>27th August 2012</strong>: TokyoTosho has been re-enabled. We're going to be fetching from both Nyaa and TokyoTosho to see how well things go.</div>
<div><strong>26th August 2012</strong>: We are now experimentally uploading some files in encrypted archives in an attempt to make files last longer. These links will only appear for logged in users on uploads which are at least about two weeks old.</div>
<div><strong>24th August 2012</strong>: With MediaFire introducing a 50GB storage cap for accounts, we will, sadly, be looking at phasing out the use of MediaFire as a service which is uploaded to.</div>
<div><strong>15th August 2012</strong>: As TokyoTosho is going a bit haywire at the moment, and I worry over the impending ID conflicts thanks to TT's backup restoration strategy, TokyoTosho fetching has been disabled for now and updates will be fetched from Nyaa.</div>
<div><strong>8th August 2012</strong>: Yes, the updates server is still down. Host has been promising that everything will be back to normal for the past 3 days whilst I've been waiting for my newly ordered server to be set up, which may take days. Whatever happens, expect updates to be dead for the next few days at least. I hope to try and catch up with everything when everything is eventually restored. Oh and a cheer for all the commenters whom breathe life into AT (or is it AP?). Thank you.</div>
<div><strong>1st August 2012</strong>: Updates server is down again, apparently due to networking issues.</div>

<div><strong>26th July 2012</strong>: We've been blocked from uploading to Jumbofiles.</div>
<div><strong>19th July 2012</strong>: TokyoTosho has been re-enabled, Nyaa disabled.</div>
<div><strong>17th July 2012</strong>: With TokyoTosho down for over two days now, fetching updates from NyaaTorrents is being tested, hoping that no problems crop up.  We will go back and fetch entries from Nyaa going back a few days from now.  Fetching from TokyoTosho has been currently disabled.</div>
<div><strong>14th June 2012</strong>: Due to some technical difficulties, updates may somewhat get stopped, delayed, or otherwise buggered for a while.</div>
<div><strong>4th June 2012</strong>: Looks like PeejeShare is here to stay. Appreciate all the feedback.</div>
<div><strong>1st June 2012</strong>: Thanks for everyone's feedback regarding PeejeShare. Due to largely positive feedback, with some uncertainty regarding limits so far, the trial period will be extended a bit.</div>
<div><strong>31st May 2012</strong>: Mediafire uploads are now wrapped in an archive. PeejeShare is being tested in place of Bayfiles - this will be reverted in ~24 hours. Please put forward any feedback you have regarding PeejeShare vs Bayfiles <a href="https://animetosho.org/feedback">on the feedback page</a>.</div>
<div><strong>31st May 2012</strong>: A number of files have now been blocked, thanks to our favourite neighbourhood media company. One Piece fans may have to look for their stuff elsewhere unfortunately.</div>
<div><strong>23rd May 2012</strong>: The limitation on batch size has been increased from 1.5GB to 3GB. Note that this is experimental.</div>
<div><strong>20th May 2012</strong>: Host being a PITA again so updates will probably be stopped for a while.</div>
<div><strong>12th May 2012</strong>: So the inevitable happened and Mediafire burnt up all our media (pun intended), causing leechers to be very sad and take out their anger against the comments system. To put it another way, you can assume most Mediafire links to be dead, and as per guidelines, don't get reuploaded by us. Now if you're an enraged leecher, you may take out your anger against the comment system and see how long it will be ignored, or try another available service.</div>
<div><strong>7th May 2012</strong>: Host for the updates server is still bitchy, so I've stopped updates and am looking into performing the tricky dance known as switching hosts. Expect updated to be paused for a while. I've ran out of apologies to give for any inconveniences, sorry.</div>
<div><strong>4th May 2012</strong>: Our hosting overlords on the updates server have found out that our inconvenience is their enjoyment. I shall try my best to fight off this evil, but in the meantime, expect <s>casualties</s> updates to stop for a while.</div>
<div><strong>2nd Apr 2012</strong>: There's some serious issues with uploading at the moment - please bear with us while it gets fixed. Updates have been disabled for now. Also, made sure not to post this along with the April 1st hubub.</div>
<div><strong>29th Mar 2012</strong>: Mediafire seem to have blocked anonymous uploads, so I'm trying to send them to an account - don't know how successful I am - expect some Mediafire downtime.  Currently trialing UploadSeeds service - only allows &lt;150MB files, and we may be banned soon, but worth a shot for now.</div>
<div><strong>11th Mar 2012</strong>: Bayfiles file size limit upped from 1GB to 4GB. Also currently trialing a script which will attempt to increase the lifespan of some links, currently restricted to Mediafire. Have no idea if it will work, or how well it will work, so will have to see. As stated in the <a href="https://animetosho.org/about">FAQs</a>, dead links aren't re-uploaded, so this will <em>only</em> try to preserve (Mediafire) links which are alive.</div>
<div><strong>2nd Mar 2012</strong>: JumboFiles and DDLAnime seem to have some reliability issues, so Bayfiles may be retained due to popular demand. Will probably trial some other hosts though, so no definite answer on this.</div>
<div><strong>2nd Mar 2012</strong>: Woot! We're back after about 3 days of downtime, thanks to a HDD failure and host not being able to repair it. The host's backup seems to be broken, so the server had to be rebuilt, however, we're relying on the host's backup for data at the moment. It seems to be okay, but if it appears to be messed up, we'll have to resort to our own backups. Apologies for the inconvenience.</div>
<div><strong>20th Feb 2012</strong>: UploadMirrors have banned us, so Bayfiles has been re-enabled in its place.</div>
<div><strong>14th Feb 2012</strong>: We now try to match files with links uploaded by <a href="http://chauthanh.info/">ChauThanh</a> as they kindly, freely provide direct downloads.</div>
<div><strong>13th Feb 2012</strong>: Some weirdness in regards to links not working correctly lately, which seems to have resolved itself. But anyway, Bayfiles seems to not be as good as it used to be, so it's been removed (if you still want it, present your case <a href="https://animetosho.org/feedback">on the Feedback page</a>) and new hosts through MirrorStack are being trialed instead. Also UploadMirrors is being tested, but they only allow 200MB parts.</div>
<div><strong>5th Feb 2012</strong>: So NyaaTorrents' tracker went down which has caused a bit of a hiccup with torrent fetching. Is somewhat fixed now, but apologies for all the recent events.</div>
<div><strong>30th Jan 2012</strong>: Updates server went up for a short period of time, then went down again. Herp.</div>
<div><strong>27th Jan 2012</strong>: The updates server has gone down and the host is currently trying to rectify the issue.</div>
<div><strong>25th Jan 2012</strong>: MegaShares disabled as Bayfiles has been added as an experimental host for files under 1GB.</div>
<div><strong>24th Jan 2012</strong>: I'm sure most of you are aware of all the recent drama surrounding file hosts. Currently, we will retain Fileserve/Filesonic etc links in the unlikely case that they 'reappear', and mark them dead at a later stage. As previously mentioned, Multiupload still doesn't appear to be working, so MegaShares has been enabled in compensation. A number of helpful users have <a href="https://animetosho.org/feedback?page=14#comment393">suggested some services</a> which I will be looking into. Depending on how things turn out, there may be a bit of host roulette coming up. As for now, hopefully EmbedUpload, Mediafire and MegaShares is enough to cover most people.</div>
<div><strong>22nd Jan 2012</strong>: Multiupload doesn't seem to be getting any better at the moment, so it's been disabled. In its place, more services are enabled through EmbedUpload. Don't have much other choice unfortunately. Updates enabled again.</div>
<div><strong>21st Jan 2012</strong>: Multiupload seems to be unstable at the moment, so many links aren't appearing. Updates have been temporarily disabled to try to assist with the load.</div>
<div><strong>13th Dec 2011</strong>: The updates server appears to be down at the moment. Trying to get it back up and running...</div>
<div><strong>11th Nov 2011</strong>: Well, it's 11/11/11 - with an overload of 1's, an update absolutely must be made. The per file upload size limit for MediaFire has been upped to 4GB, and removed for EmbedUpload. (hopefully things won't choke on this either)</div>
<div><strong>7th Nov 2011</strong>: Some stuff changed recently: fixed the link checker, which is going through the backlog of links, checking validity (note, doesn't check all hosts); magnet links are now generated from the torrent instead of being stolen from TokyoTosho, and basic auto-moderation has been implemented (so if a spam file is removed from TokyoTosho, it should eventually be deleted here).</div>
<div><strong>1st Nov 2011</strong>: NZBs are now listed for newer files, shamelessly stolen from <a href="http://www.fanzub.com/">Fanzub</a> (nice service if you like downloading from newsgroups). Also, registered users can now specify a global blacklist of items you don't want to see in the Account Settings.</div>
<div><strong>26th Oct 2011</strong>: Moved over to a new server/host - hopefully these guys keep the server running better.</div>
<div><strong>25th Oct 2011</strong>: I'd like to apologise for all the downtimes over the last few days (I've recorded 4 incidents over the last 7 days). The current host, for this website, spends too much time watching adult videos than configuring their servers properly, meaning that I'm searching for a host which knows how to keep their servers up and running (and doesn't cost a ludicrous amount like a pron subscription, to those who actually pay for pron on the interwebs, lol).</div>
<div><strong>23rd Oct 2011</strong>: ZomgUpload is problematic so disabled; testing out EmbedUpload again to see if it is more stable now</div>
<div><strong>20th Oct 2011</strong>: MegaShares has been disabled so I can test ZomgUpload (currently limited to 900MB files only); oh and sorry for the downtime earlier, which the host took a while to fix...</div>
<div><strong>18th Oct 2011</strong>: I've moved over to a new server - hopefully there aren't any issues that arise from this</div>
<div><strong>14th Oct 2011</strong>: So it seems that EmbedUpload is a rather problematic host (likes to throw errors). Until I figure out a solution, it will remain disabled. I've decided to trial MegaShares for files under 1GB in it's stead; if EmbedUpload is enabled in the future, MegaShares will probably be disabled.</div>
<div><strong>10th Oct 2011</strong>: MediaFire<s>/EmbedUpload</s> is still being uploaded to, for those wondering. Currently there's a bit of a delay getting files there - see <a href="https://animetosho.org/feedback?page=4#comment90">this comment</a> for more info. UPDATE: I've disabled EmbedUpload as it appears to be slowing things down. It may be re-enabled in the future.</div>
<div><strong>30th Sep 2011</strong>: I just realised I accidentally a script, resulting in screenshots/file info not being grabbed for the past ~2 days. Fixed now, <s>but what's lost is lost</s> I love you guys so much I decided to fix it up.</div>
<div><strong>21st Sep 2011</strong>: Uploading to EmbedUpload (multi-host uploader) is currently being trialed for files under 1GB in size.</div>
<div><strong>13th Sep 2011</strong>: The updates server is down due to a host issue, meaning that updates won't come through at the moment. Host is claiming that they are working to solve the issue.</div>
<div><strong>30th Aug 2011</strong>: There's now some rudimentary episode filtering if you can find it. Note that it's not exactly that reliable, but there if you want to use it.</div>
<div><strong>15th Aug 2011</strong>: Screenshots will now be uploaded to Imgur instead of ImageShack, due to reports of the latter being blocked by some ISPs. Also, fixed issue with screenshots not being made for Hi10P videos.</div>
<div><strong>9th Aug 2011</strong>: As pointed out by <em>Random1</em> on the <a href="https://animetosho.org/feedback">feedback page</a>, Fileserve appears to be broken now, due to a change in their upload system. If the issue gets fixed upstream, Fileserve links should automatically start appearing on <u>new</u> files</div>
<div><strong>3rd Aug 2011</strong>: A link checker script has been added - this will help pick up some old dead links, which will be displayed in red. Note that it isn't instantaneous and may take time to check all the links currently in the database</div>
<div><strong>31st Jul 2011</strong>: The backend server has finally come online again after a DC issue. Please wait for updates to propagate through, and apologies for the delays</div>
<div><strong>29th Jul 2011</strong>: Host has been doing some upgrades and shut down the server, so updates may not occur for a while</div>
<div><strong>25th Jul 2011</strong>: FileServe and FileSonic have been added as hosts</div>
<div><strong>25th Jul 2011</strong>: A number of uploads have broken due to a form change in the upstream provider. This has been resolved and broken uploads will be fixed eventually</div>
<div><strong>23rd Jul 2011</strong>: An issue with verification images not showing up has been fixed</div>

</div>
