-- drop unused stuff in anidb.* tables to speed stuff up

ALTER TABLE `_anime_http` ENGINE=BLACKHOLE;
ALTER TABLE `_lastcheck` ENGINE=BLACKHOLE;
ALTER TABLE `mylist` ENGINE=BLACKHOLE;
ALTER TABLE `review` ENGINE=BLACKHOLE;
ALTER TABLE `groupvote` ENGINE=BLACKHOLE;

ALTER TABLE `file`
DROP INDEX IF EXISTS `aid`,
DROP INDEX IF EXISTS `gid`,
DROP INDEX IF EXISTS `eid`,
DROP INDEX IF EXISTS `crc`,
DROP INDEX IF EXISTS `ed2k`;
